Login_Page
siddhantverma95/teksna-login-poc-apoorv pull request #1
Opened 2021-06-05 19:53 UTC by Apoorv-cloud

2021-06-06 07:53 UTC, siddhantverma95 requested changes

2021-06-06 07:53 UTC, siddhantverma95 commented on lib/main.dart
> +   body: Stack(
Can we use SafeArea widget here. In ios and some other android devices with notch the bottom is overlapped with home button.

2021-06-06 07:53 UTC, siddhantverma95 commented on lib/main.dart
> +            ],),)
Right now in this current situation if I want to make this whole view scrollable, I can't do that cause positioned uses particular points on screen and in scroll view there are no particular point. Plus using positioned everywhere is not a good idea for flexible design. Try to make it more flexible.. TIPS: try to use expanded and spacer widgets to achieve that.

2021-06-06 07:53 UTC, siddhantverma95 commented on lib/main.dart
> +    ));
We can use commas after every bracket to shift it automatically to the new line each. This makes code more readable for other person. Also try to use a formatter plugin that formats your code after every save. For VScode you can use Prettier plugin.

2021-06-08 15:40 UTC, closed without merging

2021-06-08 15:41 UTC, Apoorv-cloud commented
All changes done Sir